### ISSUE TITLE
Document Amazon S3 setup

### ISSUE THREAD

**Issue by programsam** [programsam/binkjs#138]
I’ve just always had S3 configured on my laptop, but when other developers start from scratch, they need to configure an S3 bucket. The docs need to have a walkthrough of how to get S3 up and running. Or provide an alternative like a docker container running an S3-compatible endpoint.

**Comment by JMarquee85** [comment]
Submitted PR to outline this process as it stands today. 

https://github.com/programsam/binkjs/pull/139

**Comment by programsam** [comment]
The above PR is merged. The only other thing here is add a note that awscli is optional, and that you can setup the credentials manually — but that might become moot if we get the other way of authenticating working.
